ScreenManagement:
    m_s: m_s # so I can use it in the .py file
    MainScreen:
        id: m_s

<MainScreen>:
    name: "main"

    BoxLayout:
        GridLayout:
            cols: 1
            Button:
                text: 'New Attribute'
                on_release: app.new_attribute()
            Button:
                text: 'Jsonify'
                on_release: app.write_to_database()
        GridLayout:
            id: attributes
            cols: 2
